name: precompile

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
    path-ignore:
      - "**/*.md"
      - "LICENSE"
      - ".gitignore"

jobs:
  precompile:
    runs-on: macos-11
    env:
      MIX_ENV: "dev"

    steps:
      - uses: actions/checkout@v3

      - name: Install Erlang/OTP, Elixir and Zig
        run: |
          brew install erlang elixir zig
          mix local.hex --force
          mix local.rebar --force

      - name: Create precompiled library
        run: |
          export FENNEC_CACHE_DIR=$(pwd)/cache
          mkdir -p "${FENNEC_CACHE_DIR}"
          mix deps.get
          mix fennec.precompile

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cache/*.tar.gz
            checksum-*.exs
